export const toBeDeleted = "";
// import { RestaurantType } from "./types";

// export const emptyRestaurant: RestaurantType = {
//   id: 0,
//   name: "",
//   description: "",
//   address: "",
//   imageUrl: "",
//   score: 0,
//   reviews: [],
// };

// export const restaurants: RestaurantType[] = [
//   {
//     id: 1,
//     name: "test1",
//     description: "lorem ipsum set dolor.",
//     address: "Oras Test, Strada Test, nr. 13",
//     imageUrl:
//       "https://media.istockphoto.com/photos/modern-restaurant-interior-design-picture-id1211547141?b=1&k=20&m=1211547141&s=612x612&w=0&h=L4QZ_Ku1LttaUtarsEERWjJIExKiTYYKrNs3ZYH4q9k=",
//     score: 3.65,
//     reviews: [
//       {
//         id: 2,
//         username: "userTest1",
//         postedOn: "10.10.2022",
//         score: 4,
//         title: "It was Good",
//         message: "Test lorem ipsum",
//         relevance: 5,
//       },
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "15.03.2021",
//         score: 3,
//         title: "It was OK",
//         message: "Test dolor set ipsum",
//         relevance: -2,
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: "test22",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque faucibus dui quis dui ullamcorper mattis. Fusce venenatis urna tellus, id pellentesque tortor convallis sed. Suspendisse ullamcorper nunc eget ipsum lobortis accumsan ac non nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam eleifend nulla vel purus tincidunt commodo. Maecenas ex dui, dignissim eget turpis sit amet, dignissim volutpat turpis. Mauris ultrices vulputate libero. Integer nec massa pharetra, congue sapien sed, fringilla arcu. Sed vel ligula turpis. Mauris facilisis nec odio ornare efficitur. Sed non euismod magna. Phasellus sit amet feugiat eros. Suspendisse porta lectus eu diam iaculis fermentum. Nunc id odio non neque molestie lacinia vel ac ante. Integer laoreet rutrum mauris, id vestibulum arcu egestas porttitor. Nam congue erat enim, at mollis neque euismod sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis porta velit eu aliquet venenatis. Sed vel mauris ac enim molestie faucibus a eget mauris. Proin vitae rutrum augue. Maecenas interdum felis non augue interdum tincidunt. Duis fringilla luctus velit venenatis sagittis. Vivamus imperdiet quam at libero viverra dapibus. Sed ultrices risus nec lacus lacinia, a finibus ipsum porta. Mauris mattis turpis sit amet pellentesque faucibus. In faucibus, velit sed vestibulum rutrum, metus erat tincidunt enim, nec ultricies risus odio sed nibh. Sed eget volutpat tortor. In ornare vestibulum suscipit. In mollis urna a mi gravida, nec tempus nisl dapibus. Mauris bibendum tristique elit. Nam sit amet nisi purus. Vestibulum eu justo tempus eros feugiat viverra. Nullam congue enim eget lobortis tincidunt..",
//     address: "Oras Test22, Strada Test23, nr. 674",
//     imageUrl:
//       "https://media-cdn.tripadvisor.com/media/photo-s/1a/b8/46/6d/london-stock.jpg",
//     score: 4.38,
//     reviews: [
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "13.11.2021",
//         score: 4,
//         title: "It was kinda good",
//         message: "Test lorem ipsum",
//         relevance: 15,
//       },
//       {
//         id: 8,
//         username: "userTest23",
//         postedOn: "18.03.2021",
//         score: 5,
//         title: "It was super good",
//         message: "Test 123 set ipsum",
//         relevance: -5,
//       },
//       {
//         id: 13,
//         username: "userTest123",
//         postedOn: "18.03.2020",
//         score: 1,
//         title: "It was NOT GOOD",
//         message: "Test dolor 444 ipsum",
//         relevance: -15,
//       },
//       {
//         id: 18,
//         username: "us erT 24s t23",
//         postedOn: "11.04.2021",
//         score: 2,
//         title: "It was super good",
//         message: "Test 123 set ipsum",
//         relevance: -5,
//       },
//       {
//         id: 113,
//         username: "userT est 123",
//         postedOn: "21.07.2020",
//         score: 3,
//         title: "It was NOT GOOD",
//         message: "Test dolor 444 ipsum",
//         relevance: -15,
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: "Some Fancy Name",
//     description: "lorem ipsum set dolor.",
//     address: "Oras Comuna, Strada Sat, nr. 871",
//     imageUrl:
//       "https://media.istockphoto.com/photos/modern-restaurant-interior-design-picture-id1211547141?b=1&k=20&m=1211547141&s=612x612&w=0&h=L4QZ_Ku1LttaUtarsEERWjJIExKiTYYKrNs3ZYH4q9k=",
//     score: 4.76,
//     reviews: [
//       {
//         id: 2,
//         username: "userTest1",
//         postedOn: "10.10.2022",
//         score: 4,
//         title: "It was Good",
//         message: "Test lorem ipsum",
//         relevance: 5,
//       },
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "15.03.2021",
//         score: 3,
//         title: "It was OK",
//         message: "Test dolor set ipsum",
//         relevance: -2,
//       },
//     ],
//   },
//   {
//     id: 4,
//     name: "Restaurantul Restaurant",
//     description: "Acesta este un restaurant de test.",
//     address: "Oras Oras, Sector Sector, Strada Strada, nr. 23674",
//     imageUrl:
//       "https://media-cdn.tripadvisor.com/media/photo-s/1a/b8/46/6d/london-stock.jpg",
//     score: 2.74,
//     reviews: [
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "13.11.2021",
//         score: 4,
//         title: "It was kinda good",
//         message: "Test lorem ipsum",
//         relevance: 15,
//       },
//       {
//         id: 8,
//         username: "userTest23",
//         postedOn: "18.03.2021",
//         score: 5,
//         title: "It was super good",
//         message: "Test 123 set ipsum",
//         relevance: -5,
//       },
//       {
//         id: 13,
//         username: "userTest123",
//         postedOn: "18.03.2020",
//         score: 1,
//         title: "It was NOT GOOD",
//         message: "Test dolor 444 ipsum",
//         relevance: -15,
//       },
//     ],
//   },
//   {
//     id: 5,
//     name: "test1123211233213",
//     description: "lorem ipsum set dolor.",
//     address: "Oras Test, Strada Test, nr. 13",
//     imageUrl:
//       "https://media.istockphoto.com/photos/modern-restaurant-interior-design-picture-id1211547141?b=1&k=20&m=1211547141&s=612x612&w=0&h=L4QZ_Ku1LttaUtarsEERWjJIExKiTYYKrNs3ZYH4q9k=",
//     score: 1.25,
//     reviews: [
//       {
//         id: 2,
//         username: "userTest1",
//         postedOn: "10.10.2022",
//         score: 4,
//         title: "It was Good",
//         message: "Test lorem ipsum",
//         relevance: 5,
//       },
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "15.03.2021",
//         score: 3,
//         title: "It was OK",
//         message: "Test dolor set ipsum",
//         relevance: -2,
//       },
//     ],
//   },
//   {
//     id: 6,
//     name: "t34esfffxxt22",
//     description: "Acesta este un restaurant de test.",
//     address: "Oras Test22, Strada Test23, nr. 674",
//     imageUrl:
//       "https://media-cdn.tripadvisor.com/media/photo-s/1a/b8/46/6d/london-stock.jpg",
//     score: 2.75,
//     reviews: [
//       {
//         id: 5,
//         username: "userTest2",
//         postedOn: "13.11.2021",
//         score: 4,
//         title: "It was kinda good",
//         message: "Test lorem ipsum",
//         relevance: 15,
//       },
//       {
//         id: 8,
//         username: "userTest23",
//         postedOn: "18.03.2021",
//         score: 5,
//         title: "It was super good",
//         message: "Test 123 set ipsum",
//         relevance: -5,
//       },
//       {
//         id: 13,
//         username: "userTest123",
//         postedOn: "18.03.2020",
//         score: 1,
//         title: "It was NOT GOOD",
//         message: "Test dolor 444 ipsum",
//         relevance: -15,
//       },
//     ],
//   },
// ];
